### PR TITLE
fix(gradle-plugin): add .convention() defaults to Property<T> fields in ResolveTask

### LINKED ISSUE #5136: [Bug]: Gradle 9 fails to use the lib because of the missing `convention`
In Gradle 9, calling `Property<T>.get()` on a property that has neither a set value nor a convention throws at runtime:

> Cannot query the value of task property '...' because it has no value available.

`ResolveTask.resolve()` calls `.get()` unconditionally on `prettyPrint`, `readAllResources`, `sortOutput`, `alwaysResolveAppPath`, `skipResolveAppPath`, and `encoding`. None had a `.convention(...)` default, so they throw when not explicitly set by the caller.

### PR DESCRIPTION
**Pull request by lfgcampos**
# Pull Request

Thank you for contributing to **swagger-core**!

Please fill out the following information to help us review your PR efficiently.

---

Closes #5136

## Description

In Gradle 9, calling `Property<T>.get()` on a property that has neither a set value nor a convention throws at runtime:

> Cannot query the value of task property '...' because it has no value available.

`ResolveTask.resolve()` calls `.get()` unconditionally on `prettyPrint`, `readAllResources`, `sortOutput`, `alwaysResolveAppPath`, `skipResolveAppPath`, and `encoding`. None had a `.convention(...)` default, so they throw when not explicitly set by the caller.

Fix: add `.convention(false)` to the five boolean fields and `.convention(StandardCharsets.UTF_8.name())` to encoding. Callers that set these explicitly are unaffected.

| Property | Type | Convention | Notes |
| --- | --- | --- | --- |
| `outputFileName` | `Property<String>` | `"openapi"` | Was unguarded `.get()` |
| `outputFormat` | `Property<Format>` | `Format.JSON` | Was unguarded `.get()` |
| `prettyPrint` | `Property<Boolean>` | `false` | Matches `SwaggerPlugin` |
| `readAllResources` | `Property<Boolean>` | `false` | Matches `SwaggerPlugin` |
| `encoding` | `Property<String>` | `Charset.defaultCharset().name()` | Matches `SwaggerPlugin` |
| `sortOutput` | `Property<Boolean>` | `false` | Matches `SwaggerPlugin` |
| `alwaysResolveAppPath` | `Property<Boolean>` | `false` | Matches `SwaggerPlugin` |
| `skipResolveAppPath` | `Property<Boolean>` | `false` | Matches `SwaggerPlugin` |
| `skip` | `Property<Boolean>` | `false` | Already safe via `.getOrElse()`, added for consistency |
| `openAPI31` | `Property<Boolean>` | `false` | Matches `SwaggerPlugin` |
| `convertToOpenAPI31` | `Property<Boolean>` | `false` | Fixes latent bug: `.get()` at line 578 had no `isPresent()` guard |

## Type of Change

- [X] 🐛 Bug fix
- [ ] ✨ New feature
- [ ] ♻️ Refactor (non-breaking change)
- [X] 🧪 Tests
- [ ] 📝 Documentation
- [ ] 🧹 Chore (build or tooling)

## Checklist

- [X] I have added/updated tests as needed
- [ ] I have added/updated documentation where applicable
- [X] The PR title is descriptive
- [X] The code builds and passes tests locally
- [X] I have linked related issues (if any)

### CODE REVIEW

**Comment by ewaostrowska** [comment]
Hi @lfgcampos! Thanks for pointing this issue out and putting your effort to resolve it. 
I have few remarks regarding this issue that I would like fixed before merging this PR:
1) There's no issue linked for this PR. Please create one and link it in this PR if such issue does not exist yet. This is our main way of documenting and tracking the changes 
2) There seems to be few other cases that potentially could be included in this PR. Please include them or at least address them 
3) No tests for either Gradle 9 or other Gradle versions

File: modules/swagger-gradle-plugin/src/main/java/io/swagger/v3/plugins/gradle/tasks/ResolveTask.java [hunk 1]
```diff
@@ -86,7 +87,7 @@ public enum Format {JSON, YAML, JSONANDYAML}
     @Input
     @Optional
 
-    public final Property<String> encoding = getProject().getObjects().property(String.class);
+    public final Property<String> encoding = getProject().getObjects().property(String.class).convention(StandardCharsets.UTF_8.name());
```
[the remark this answers is not in the document]
Comment (lfgcampos) [reply modules/swagger-gradle-plugin/src/main/java/io/swagger/v3/plugins/gradle/tasks/ResolveTask.java]: done

**Comment by lfgcampos** [comment]
> Hi @lfgcampos! Thanks for pointing this issue out and putting your effort to resolve it. I have few remarks regarding this issue that I would like fixed before merging this PR:
> 
> 1. There's no issue linked for this PR. Please create one and link it in this PR if such issue does not exist yet. This is our main way of documenting and tracking the changes
> 2. There seems to be few other cases that potentially could be included in this PR. Please include them or at least address them
> 3. No tests for either Gradle 9 or other Gradle versions

hi @ewaostrowska, thanks for the comments and review!

1. done, issue created and linked
2. I've covered another 5 ones that I figured would benefit from. There might be more but I can't possibly define a default sensible value without changing behavious
3. Added something, hope it is enough!

Also updated the description with a lot more info 🤞

**Review by daniel-kmiecik — APPROVED** [review]

File: modules/swagger-gradle-plugin/src/main/java/io/swagger/v3/plugins/gradle/tasks/ResolveTask.java [hunk 2]
```diff
@@ -61,10 +62,10 @@ public enum Format {JSON, YAML, JSONANDYAML}
     public final Property<String> scannerClass = getProject().getObjects().property(String.class);
     @Input
     @Optional
-    public final Property<Boolean> prettyPrint = getProject().getObjects().property(Boolean.class);
+    public final Property<Boolean> prettyPrint = getProject().getObjects().property(Boolean.class).convention(false);
```
Comment (ewaostrowska) [inline modules/swagger-gradle-plugin/src/main/java/io/swagger/v3/plugins/gradle/tasks/ResolveTask.java]: https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-gradle-plugin/README.md#parameters the .convention should be set to TRUE according to the documentation.

Comment (lfgcampos) [reply modules/swagger-gradle-plugin/src/main/java/io/swagger/v3/plugins/gradle/tasks/ResolveTask.java]: fixed

**Review by ewaostrowska — APPROVED** [review]

**Comment by ewaostrowska** [comment]
Thanks for the PR and great cooperation @lfgcampos!
