### PR TITLE
Fixed #1069: Handling of generic types has been added.

### LINKED ISSUE #1069: Parameters of generic collection types are reported incorrectly in swagger.json
Swagger version is 1.5.2-M2-SNAPSHOT (branch `develop_2.0`)
This test resource:
```
@Api
@Path("/generics")
public class ResourceWithGenerics {

  @POST
  @Path("/testStringsSet")
  @ApiOperation("Tests set of strings")
  public void testStringsSet(@HeaderParam("input") @ApiParam Set<String> input) {
  }

  @POST
  @Path("/testObjectsSet")
  @ApiOperation("Tests set of objects")
  public void testObjectsSet(@HeaderParam("input") @ApiParam Set<Tag> input) {
  }

  @POST
  @Path("/testStringsList")
  @ApiOperation("Tests list of strings")
  public void testStringsList(@HeaderParam("input") @ApiParam List<String> input) {
  }

  @POST
  @Path("/testObjectsList")
  @ApiOperation("Tests list of objects")
  public void testObjectsList(@HeaderParam("input") @ApiParam List<Tag> input) {
  }
}
```
is reported as follows:
```
{
  "swagger" : "2.0",
  "paths" : {
    "/generics/testObjectsList" : {
      "post" : {
        "summary" : "Tests list of objects",
        "description" : "",
        "operationId" : "testObjectsList",
        "parameters" : [ {
          "name" : "input",
          "in" : "header",
          "description" : "",
          "required" : false,
          "type" : "array",
          "collectionFormat" : "multi",
          "default" : ""
        } ],
        "responses" : {
          "default" : {
            "description" : "successful operation"
          }
        }
      }
    },
    "/generics/testObjectsSet" : {
      "post" : {
        "summary" : "Tests set of objects",
        "description" : "",
        "operationId" : "testObjectsSet",
        "parameters" : [ {
          "name" : "input",
          "in" : "header",
          "description" : "",
          "required" : false,
          "type" : "array",
          "default" : ""
        } ],
        "responses" : {
          "default" : {
            "description" : "successful operation"
          }
        }
      }
    },
    "/generics/testStringsList" : {
      "post" : {
        "summary" : "Tests list of strings",
        "description" : "",
        "operationId" : "testStringsList",
        "parameters" : [ {
          "name" : "input",
          "in" : "header",
          "description" : "",
          "required" : false,
          "type" : "array",
          "collectionFormat" : "multi",
          "default" : ""
        } ],
        "responses" : {
          "default" : {
            "description" : "successful operation"
          }
        }
      }
    },
    "/generics/testStringsSet" : {
      "post" : {
        "summary" : "Tests set of strings",
        "description" : "",
        "operationId" : "testStringsSet",
        "parameters" : [ {
          "name" : "input",
          "in" : "header",
          "description" : "",
          "required" : false,
          "type" : "array",
          "default" : ""
        } ],
        "responses" : {
          "default" : {
            "description" : "successful operation"
          }
        }
      }
    }
  }
}
```
The `items` node is missing.

### PR DESCRIPTION
**Pull request by tomtit**
Fixed #1069: Handling of generic types has been added.
* The `com.wordnik.swagger.jaxrs.ext.SwaggerExtension` interface was reworked to use generic `Type` instead of raw `Class<?>`
* Added `PropertyBuilder.merge(...)` method for `ParameterProcessor`
* `ParameterProcessor` forces non-body parameters to be of primitive type

### CODE REVIEW

File: modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/DefaultParameterExtension.java [hunk 1]
```diff
@@ -102,12 +97,23 @@ else if(annotation instanceof FormParam) {
...
-  public boolean shouldIgnoreClass(Class<?> cls) {
-    boolean output = false;
-    if(cls.getName().startsWith("javax.ws.rs"))
-      output = true;
-    else
-      output = false;
-    return output;
+  @Override
+  protected boolean shouldIgnoreClass(Class<?> cls) {
+    return cls.getName().startsWith("javax.ws.rs.");
```
Comment (tomtit) [inline modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/DefaultParameterExtension.java]: Changed `rs` to `rs.` to skip `javax.ws.rs.*` classes only.
Removed state variable to get shorter body.

File: modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/DefaultParameterExtension.java [hunk 2]
```diff
@@ -102,12 +97,23 @@ else if(annotation instanceof FormParam) {
...
+  }
+
+  private Property createProperty(Type type) {
+    return enforcePrimitive(ModelConverters.getInstance().readAsProperty(type));
```
Comment (tomtit) [inline modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/DefaultParameterExtension.java]: non-body params have to be of primitive type according to our spec.

File: modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/DefaultParameterExtension.java [hunk 3]
```diff
@@ -19,16 +16,14 @@
 import javax.ws.rs.CookieParam;
 import javax.ws.rs.FormParam;
 import javax.ws.rs.DefaultValue;
-import javax.ws.rs.Consumes;
-import javax.ws.rs.Produces;
 
-public class DefaultParameterExtension extends AbstractSwaggerExtension implements SwaggerExtension {
-  Logger LOGGER = LoggerFactory.getLogger(DefaultParameterExtension.class);
+public class DefaultParameterExtension extends AbstractSwaggerExtension {
```
Comment (tomtit) [inline modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/DefaultParameterExtension.java]: `implements SwaggerExtension` was moved into base class

File: modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/DefaultParameterExtension.java [hunk 4]
```diff
@@ -19,16 +16,14 @@
...
 
-  public List<Parameter> extractParameters(Annotation[] annotations, Class<?> cls, boolean isArray, Set<Class<?>> classesToSkip, Iterator<SwaggerExtension> chain) {
+  @Override
+  public List<Parameter> extractParameters(List<Annotation> annotations, Type type, Set<Type> typesToSkip, Iterator<SwaggerExtension> chain) {
     String defaultValue = "";
 
-    if(this.shouldIgnoreClass(cls))
+    if(shouldIgnoreType(type, typesToSkip))
```
Comment (tomtit) [inline modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/DefaultParameterExtension.java]: Need to add skipped type into `typesToSkip`

File: modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ParameterProcessor.java [hunk 5]
```diff
@@ -73,26 +76,37 @@ public static Parameter applyAnnotations(Swagger swagger, Parameter parameter, C
...
-          processAllowedValues(allowableValues, true, args);
-        }
-
-        p.items(PropertyBuilder.build(p.getType(), p.getFormat(), args))
-          .type(ArrayProperty.TYPE)
-          .format(null)
-          .collectionFormat("multi");
+        processAllowedValues(allowableValues, true, args);
+        PropertyBuilder.merge(p.getItems(), args);
+        p.collectionFormat("csv");
```
Comment (tomtit) [inline modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ParameterProcessor.java]: Default value is `csv` according to the spec.
`multi` is valid only for `query` or `formData` only.

File: modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ParameterProcessor.java [hunk 6]
```diff
@@ -73,26 +76,37 @@ public static Parameter applyAnnotations(Swagger swagger, Parameter parameter, C
...
-        if (allowableValues != null) {
-          processAllowedValues(allowableValues, true, args);
-        }
-
-        p.items(PropertyBuilder.build(p.getType(), p.getFormat(), args))
-          .type(ArrayProperty.TYPE)
-          .format(null)
-          .collectionFormat("multi");
+        processAllowedValues(allowableValues, true, args);
+        PropertyBuilder.merge(p.getItems(), args);
```
Comment (tomtit) [inline modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ParameterProcessor.java]: StringProperty may contain enum values, so let's merge additional arguments instead of rebuilding items from scratch.

File: modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ParameterProcessor.java [hunk 7]
```diff
@@ -143,29 +152,25 @@ public static Parameter applyAnnotations(Swagger swagger, Parameter parameter, C
...
-              else
-                bp.setSchema(new RefModel().asDefault(name));
-              if(swagger != null)
+              bp.setSchema(new RefModel().asDefault(name));
+              if(swagger != null) {
                 swagger.addDefinition(name, models.get(name));
+              }
             }
           }
-          models = ModelConverters.getInstance().readAll(cls);
```
Comment (tomtit) [inline modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ParameterProcessor.java]: We need to call `readAll` when `swagger != null`

File: modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java [hunk 8]
```diff
@@ -59,7 +59,6 @@
 
   Swagger swagger;
   private final ReaderConfig config;
-  static ObjectMapper m = Json.mapper();
```
Comment (tomtit) [inline modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java]: Never used.

File: modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java [hunk 9]
```diff
@@ -566,15 +565,11 @@ else if(!responseClass.equals(java.lang.Void.class) && !"void".equals(responseCl
       hidden = apiOperation.hidden();
 
     // process parameters
-    Class[] parameterTypes = method.getParameterTypes();
```
Comment (tomtit) [inline modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java]: We don't need raw types here

File: modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ext/SwaggerExtension.java [hunk 10]
```diff
@@ -1,14 +1,16 @@
...
+import com.wordnik.swagger.annotations.ApiOperation;
+import com.wordnik.swagger.models.parameters.Parameter;
 
 public interface SwaggerExtension {
   String extractOperationMethod(ApiOperation apiOperation, Method method, Iterator<SwaggerExtension> chain);
-  List<Parameter> extractParameters(Annotation[] annotations, Class<?> cls, boolean isArray, Set<Class<?>> classesToSkip, Iterator<SwaggerExtension> chain);
-  boolean shouldIgnoreClass(Class<?> cls);
-}
\ No newline at end of file
+  List<Parameter> extractParameters(List<Annotation> annotations, Type type, Set<Type> typesToSkip, Iterator<SwaggerExtension> chain);
```
Comment (tomtit) [inline modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ext/SwaggerExtension.java]: Changed `Class<?>` to `Type`, `Set<Class<?>>` to `Set<Type>`.
`isArray` is redundant as it's known from `Type`.

File: modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ext/SwaggerExtension.java [hunk 11]
```diff
@@ -1,14 +1,16 @@
...
+import java.util.List;
+import java.util.Set;
+
+import com.wordnik.swagger.annotations.ApiOperation;
+import com.wordnik.swagger.models.parameters.Parameter;
 
 public interface SwaggerExtension {
   String extractOperationMethod(ApiOperation apiOperation, Method method, Iterator<SwaggerExtension> chain);
-  List<Parameter> extractParameters(Annotation[] annotations, Class<?> cls, boolean isArray, Set<Class<?>> classesToSkip, Iterator<SwaggerExtension> chain);
-  boolean shouldIgnoreClass(Class<?> cls);
```
Comment (tomtit) [inline modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ext/SwaggerExtension.java]: `shouldIgnoreClass` was moved into AbstractSwaggerExtension as we use it inside implementations only. I think we can do this as we changing the signature already.

File: modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java [hunk 12]
```diff
@@ -586,51 +581,38 @@ else if(!responseClass.equals(java.lang.Void.class) && !"void".equals(responseCl
...
-            if(param != null) {
-              parameters.add(param);
-            }            
-          }
-        }
-        else {
-          Parameter param = ParameterProcessor.applyAnnotations(swagger, null, cls, annotations, isArray);
-          if(param != null) {
-            parameters.add(param);
-          }
```
Comment (tomtit) [inline modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java]: The `ParameterProcessor.applyAnnotations` knows how to handle generics now.

File: modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ParameterProcessor.java [hunk 13]
```diff
@@ -143,29 +152,25 @@ public static Parameter applyAnnotations(Swagger swagger, Parameter parameter, C
...
           }
         }
-      }
-      else {
-        Map<String, Model> models = ModelConverters.getInstance().read(cls);
+      } else {
+        Map<String, Model> models = ModelConverters.getInstance().read(type);
         if(models.size() > 0) {
           for(String name: models.keySet()) {
             if(name.indexOf("java.util") == -1) {
```
Comment (tomtit) [inline modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ParameterProcessor.java]: `isArray` was always `false` here, need to leave the `else` block only.

File: modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java [hunk 14]
```diff
@@ -586,51 +581,38 @@ else if(!responseClass.equals(java.lang.Void.class) && !"void".equals(responseCl
     return operation;
   }
 
-  List<Parameter> getParameters(Class<?> cls, Type type, Annotation[] annotations) {
-    // look for path, query
-    boolean isArray = ParameterUtils.isMethodArgumentAnArray(cls, type);
```
Comment (tomtit) [inline modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/Reader.java]: `isArray` is known from `type`

File: modules/swagger-jaxrs/src/test/scala/SimpleScannerTest.scala [hunk 15]
```diff
@@ -152,6 +152,8 @@ class SimpleScannerTest extends FlatSpec with Matchers {
     v0.getEnum().asScala.toSet should be (allEnumValues)
     val v1 = checkEnumHandling.get(1).asInstanceOf[SerializableParameter]
     v1.getItems().asInstanceOf[StringProperty].getEnum().asScala.toSet should be (allEnumValues)
+    val v2 = checkEnumHandling.get(2).asInstanceOf[SerializableParameter]
+    v2.getItems().asInstanceOf[StringProperty].getEnum().asScala.toSet should be (allEnumValues)
```
Comment (tomtit) [inline modules/swagger-jaxrs/src/test/scala/SimpleScannerTest.scala]: Now we have `enum` array, let's check if it contains all values

File: modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ext/AbstractSwaggerExtension.java [hunk 16]
```diff
@@ -1,33 +1,53 @@
...
     else
-      return null;
+      return Collections.emptyList();
+  }
+
+  protected boolean shouldIgnoreClass(Class<?> cls) {
+    return false;
   }
 
-  public boolean shouldIgnoreClass(Class<?> cls) {
```
Comment (tomtit) [inline modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ext/AbstractSwaggerExtension.java]: Let's force all descendants to register skipped types in `typesToSkip` set

File: modules/swagger-jersey2-jaxrs/src/main/java/com/wordnik/swagger/jersey/SwaggerJersey2Jaxrs.java [hunk 17]
```diff
@@ -83,37 +73,31 @@
...
+          List<Parameter> extracted =
+              extensions.next().extractParameters(paramAnnotations, paramType, typesToSkip, extensions);
 
           // since downstream processors won't know how to introspect @BeanParam, process here
-          for(Parameter param : extracted)
-            ParameterProcessor.applyAnnotations(null, param, paramClass, paramAnnotations.toArray(new Annotation[paramAnnotations.size()]), isArray);
-
-          parameters.addAll(extracted);
+          for(Parameter param : extracted) {
+            if (ParameterProcessor.applyAnnotations(null, param, paramType, paramAnnotations) != null) {
```
Comment (tomtit) [inline modules/swagger-jersey2-jaxrs/src/main/java/com/wordnik/swagger/jersey/SwaggerJersey2Jaxrs.java]: The `ParameterProcessor.applyAnnotations` call may return `null` for skipped parameters, so let's skip them too.

File: modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/RefProperty.java [hunk 18]
```diff
@@ -56,7 +57,7 @@ public String getSimpleRef() {
   }
 
   public static boolean isType(String type, String format) {
```
Comment (tomtit) [inline modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/RefProperty.java]: This was always `false` as `"$ref" != "ref"`.
Need this change for `PropertyBuilder.Processor.REFERENCE.isType`

File: modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/IntegerProperty.java [hunk 19]
```diff
@@ -3,10 +3,11 @@
 import com.wordnik.swagger.models.Xml;
 
 public class IntegerProperty extends AbstractNumericProperty implements Property {
```
Comment (tomtit) [inline modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/IntegerProperty.java]: Need this constant for `PropertyBuilder.Processor.INTEGER.isType`

File: modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/IntegerProperty.java [hunk 20]
```diff
@@ -3,10 +3,11 @@
...
+  public static final String TYPE = "integer";
```
Comment (tomtit) [inline modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/IntegerProperty.java]: Need this constant for `PropertyBuilder.Processor.INTEGER.isType`

File: modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ParameterProcessor.java (hunk 5 above)
Comment (olensmar) [inline modules/swagger-jaxrs/src/main/java/com/wordnik/swagger/jaxrs/ParameterProcessor.java]: perhaps have a constant - DEFAULT_COLLECTION_FORMAT ?

File: modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/IntegerProperty.java [hunk 21]
```diff
@@ -3,10 +3,11 @@
...
   protected Integer _default;
 
   public IntegerProperty() {
-    super.type = "integer";
+    super.type = TYPE;
     super.format = "int32";
```
Comment (olensmar) [inline modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/IntegerProperty.java]: why not have a FORMAT constant also?

Comment (tomtit) [inline modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/IntegerProperty.java]: @olensmar, I don't need it for this fix. Do you want me to add it?

**Comment by olensmar** [comment]
Looks great to me - Ron, if you have nothing please merge

File: modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/IntegerProperty.java (hunk 21 above)
Comment (olensmar) [inline modules/swagger-models/src/main/java/com/wordnik/swagger/models/properties/IntegerProperty.java]: no - i'm just just nitpicking :-)
